default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: urlshort_api_development

test:
  <<: *default
  database: urlshort_api_test

production:
  <<: *default
  database: urlshort_api_production
  username: urlshort_api
  password: <%= ENV['URLSHORT_API_DATABASE_PASSWORD'] %>
